services:
  voice-chat:
    build: .
    devices:
      - /dev/snd:/dev/snd
      - /dev/input:/dev/input
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority
    network_mode: host
    privileged: true
    restart: unless-stopped