services:
  voice-chat:
    build: .
    environment:
      - PYNPUT_BACKEND=evdev
    devices:
      - /dev/snd:/dev/snd
      - /dev/input:/dev/input
    volumes:
      - /run/udev:/run/udev:ro
    network_mode: host
    privileged: true
    user: root
    restart: unless-stopped